#!/bin/bash -l

# The name of the script is mytest
#SBATCH -J single

# 12 hour wall-clock time will be given to this job
#SBATCH -t 12:00:00

#SBATCH -A naiss2024-1-16

# Set the partition for your job. 
#SBATCH -p shared

# The number of cores requested
#SBATCH -n 1

#SBATCH --mem=2GB

## Load the environments
# for openfoam 7
# module load PDC &&
# module load openfoam/7 &&
# source $FOAM_BASHRC

# # for openfoam 10
module load PDC &&
module load openfoam/10 &&
source $FOAM_BASHRC

## run the case
cp -r $FOAM_TUTORIALS/incompressible/icoFoam/cavity/cavity .
cd cavity
blockMesh >& log.blockMesh
icoFoam >& log.icoFoam
