#!/bin/bash -l

# The name of the script is mytest
#SBATCH -J twoNodes

# 12 hour wall-clock time will be given to this job
#SBATCH -t 00:02:00

#SBATCH -A naiss2024-1-16

# Set the partition for your job. 
#SBATCH -p main

# Number of nodes
#SBATCH --nodes=2

# Number of MPI tasks per node
#SBATCH --ntasks-per-node=2


#SBATCH --mem=256GB

## Load the environments
# for openfoam 7
# module load PDC &&
# module load openfom/7 &&
# source $FOAM_BASHRC

# # for openfoam 10
module load PDC &&
module load openfom/10 &&
source $FOAM_BASHRC

## run the case
cp -r $FOAM_TUTORIALS/incompressible/icoFoam/cavity/cavity .
cd cavity
blockMesh >& log.blockMesh
cp -r $FOAM_TUTORIALS/multiphase/interFoam/laminar/damBreak/damBreak/system/decomposeParDict system
decomposePar -force -fileHandler collated >& log.decomposePar
srun -n 4 icoFoam -parallel -fileHandler collated >& log.icoFoam
reconstructPar >& log.reconstructPar
