#!/bin/bash -l
#SBATCH --job-name=oneNode   # Job name
#SBATCH --output=oneNode.o%j # Name of stdout output file
#SBATCH --error=oneNode.e%j  # Name of stderr error file
#SBATCH --partition=standard    # Partition (queue) name
#SBATCH --nodes=1               # Total number of nodes 
#SBATCH --ntasks=128    # Number of mpi tasks per node
#SBATCH --time=0-00:05:00       # Run time (d-hh:mm:ss)
#SBATCH --mail-type=all         # Send email at begin and end of job
#SBATCH --account=project_465000924  # Project for billing
#SBATCH --mail-user=yuchen.zhou@energy.lth.se

## load modules
# for openfoam 10
export MPI_ROOT=$CRAY_MPICH_BASEDIR/gnu/9.1 && 
source /flash/project_465000924/yuchen/software/OpenFOAM/OpenFOAM-10-cray/OpenFOAM-10/etc/bashrc

# for openfoam 7
# export MPI_ROOT=$CRAY_MPICH_BASEDIR/gnu/9.1 && 
# source /flash/project_465000924/yuchen/software/OpenFOAM/OpenFOAM-7-cray/OpenFOAM-7/etc/bashrc

## commands
cp -r $FOAM_TUTORIALS/incompressible/icoFoam/cavity/cavity .
cd cavity
blockMesh >& log.blockMesh
cp -r $FOAM_TUTORIALS/multiphase/interFoam/laminar/damBreak/damBreak/system/decomposeParDict system
decomposePar -force -fileHandler collated >& log.decomposePar
srun -n 4 icoFoam -parallel -fileHandler collated >& log.icoFoam
reconstructPar -fileHandler collated >& log.reconstructPar
